repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: migrations/
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        exclude: migrations/
        args:
          - --line-length=88
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: migrations/
        args:
          - --profile=black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: migrations/
        args:
          - "--max-line-length=88"
          - "--ignore=E203, E501, W503, E731, C408, C403 SIM102, SIM114, SIM105, SIM113, SIM115, W605, B009, B010, F541, F841"
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
        exclude: migrations/
  - repo: local
    hooks:
      - id: conventional-commit-check
        name: 'Conventional Commit Check'
        entry: ./check-commit-msg/run-conventional-commit-check.sh
        language: 'script'
        description: "Checks that your 'git commit' matches the 'Conventional Commits' standard"
        always_run: true
        stages: [ commit-msg ]
