version: "3"

services:
  web:
    build:
      context: .
      dockerfile: docker/prod/django/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - docker/prod/django/.env
    volumes:
      - ./media:/app/media
      - ./apps:/app/apps
      - redis_socket:/redis_socket
    depends_on:
      - db
      - redis

  db:
    image: postgres:14.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    env_file:
      - docker/local/postgres/.env

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 50s
      timeout: 5s
      retries: 5

  redis:
    build:
      context: .
      dockerfile: docker/local/redis/Dockerfile
    restart: unless-stopped
    volumes:
      - redis_data:/data
      - redis_socket:/redis_socket
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1m20s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  redis_socket:
