# Generated by Django 4.2.9 on 2024-06-15 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gameplayed",
            options={
                "verbose_name": "Cыгранная игры",
                "verbose_name_plural": "Сыгранные игры",
            },
        ),
        migrations.AlterField(
            model_name="gameplayed",
            name="score",
            field=models.PositiveBigIntegerField(default=0, verbose_name="Счёт"),
        ),
        migrations.AlterField(
            model_name="gameplayed",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Имя пользователя",
            ),
        ),
    ]
