# Generated by Django 4.2.9 on 2024-06-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_customuser_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_pick",
            field=models.ImageField(
                null=True, upload_to="media/game_2048/profile_pic/{self.username}"
            ),
        ),
    ]
