# Generated by Django 4.2.9 on 2024-06-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_customuser_profile_pick"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pick",
            field=models.ImageField(
                null=True, upload_to="", verbose_name="Фото пользователя"
            ),
        ),
    ]
