# Generated by Django 4.2.9 on 2024-06-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_customuser_profile_pick"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile_pick",
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(
                null=True,
                upload_to="path_and_rename('game_2048/profile_picture/')",
                verbose_name="Фото пользователя",
            ),
        ),
    ]
